%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\User\Documents\MATLAB\mdm3\bmw1.csv
%
% Auto-generated by MATLAB on 19-Mar-2020 13:54:32

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ProductID", "Productcharacteristic1", "QualityCharacteristic8", "QualityCharacteristic1", "QualityCharacteristic2", "QualityCharacteristic3", "QualityCharacteristic4", "QualityCharacteristic5", "QualityCharacteristic6", "ProcessCharacteristic1", "ProcessCharacteristic2", "Reworkcharacteristic1", "Reworkcharacteristic2", "Repaircharacteristic1", "ReworkMinutes", "Qualityrating", "CaptureDate", "ReworkDate", "QualityCharacteristic7"];
opts.VariableTypes = ["double", "double", "categorical", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "categorical", "categorical", "categorical", "double", "double", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["CaptureDate", "ReworkDate"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["QualityCharacteristic8", "QualityCharacteristic5", "QualityCharacteristic6", "Reworkcharacteristic1", "Reworkcharacteristic2", "Repaircharacteristic1", "CaptureDate", "ReworkDate"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ProcessCharacteristic1", "TrimNonNumeric", true);
opts = setvaropts(opts, "ProcessCharacteristic1", "ThousandsSeparator", ",");

% Import the data
bmw1 = readtable("C:\Users\User\Documents\MATLAB\mdm3\bmw1.csv", opts);


%% Clear temporary variables
clear opts

for i = 1:18913
    if strcmp(bmw1(i,14),'b');
        bmw1(i,:) = []
    end
end
